### ISSUE TITLE
Function definition after the return statement

### ISSUE THREAD

**Issue by eight04** [bcoe/c8#66]
* **Version**: v11.10.0
* **Platform**: Windows 7 x64

1. Create *foo.js*:
    ```js
    function test(foo = "foo") {
      return {bar};
      
      function bar() {
        console.log("test");
      }
    }

    test().bar();
    ```
2. Run `c8 --reporter html node foo.js`
3. Line 3, 4 are marked as uncovered:
    ![image](https://user-images.githubusercontent.com/1324510/52922996-26a90980-3360-11e9-907c-6fa464fec932.png)
    
It works fine if `test` has no default argument:
![image](https://user-images.githubusercontent.com/1324510/52923018-51935d80-3360-11e9-8d6d-837541a04882.png)

c8 v3.4.0

**Comment by eight04** [comment]
This bug also applies to async function without default arguments:
```js
async function test(foo) {
  return {bar};
  
  function bar() {
    console.log("test");
  }
}

test().then(r => r.bar());
```
![image](https://user-images.githubusercontent.com/1324510/56357654-dee31900-620e-11e9-9a3c-d5d44fb1c18b.png)

**Comment by bcoe** [comment]
@eight04 could you please try with Node@12.0, or a never version of 11; I believe this issue has been addressed  upstream.

**Comment by eight04** [comment]
I can still reproduce this issue with Node@12.1.0 + c8@4.0.0.

**Comment by bcoe** [comment]
@schuay ping, this looks like it might trace back to some oddities in V8.

**Comment by schuay** [comment]
Are microtasks run to completion before reporting coverage? I tried this locally in d8 and indeed just running the script does not show coverage for `bar`. But after flushing microtasks with `%PerformMicrotaskCheckpoint();` (pass `--allow-natives-syntax`) the counts show up correctly.

I'm not familiar with how coverage is collected in node. Do you collect after completing all microtasks?

**Comment by bcoe** [comment]
@schuay interesting; it sounds like we might need to change our implementation in Node.js to force micro tasks to complete (CC: @joyee).

**Comment by bcoe** [comment]
@schuay coming back to some old issues, this still seems to have issues in Node 13:

```
%PerformMicrotaskCheckpoint();
function test(foo = "foo") {
  return {bar};
  
  function bar() {
    console.log("test");
  }
}

test().bar();
```

```
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |       80 |       75 |      100 |       80 |                   |
 foo.js   |       80 |       75 |      100 |       80 |               4,5 |
----------|----------|----------|----------|----------|-------------------|
```

**Comment by joyeecheung** [comment]
I think the question is whether we actually want to flush the microtasks at exit - in the case of e.g. uncaught excetions, this might not be desirable (because that may trigger more exceptions/rejections that are treated as exceptions by us). However we should be able to flush them when we are on the normal exit path.

**Comment by bcoe** [comment]
@joyeecheung I tried, on Jakob's suggestion, enabling natives syntax, and calling `%PerformMicrotaskCheckpoint();` in the test script, and it's worth noting it didn't seem to do the trick.

@joyeecheung, I was thinking for some of these issues I'll perhaps open a tracking issue in V8, okay if I loop you in? or can you suggest someone else?

**Comment by joyeecheung** [comment]
Indeed, I tried this ad-hoc fix on Node.js master and it did not seem to work

```
diff --git a/src/inspector_profiler.cc b/src/inspector_profiler.cc
index b5f63b2b41..8e760063a1 100644
--- a/src/inspector_profiler.cc
+++ b/src/inspector_profiler.cc
@@ -369,6 +369,7 @@ void EndStartedProfilers(Environment* env) {
   if (connection != nullptr && !connection->ending()) {
     Debug(
         env, DebugCategory::INSPECTOR_PROFILER, "Ending coverage collection\n");
+    env->isolate()->RunMicrotasks();
     connection->End();
   }
 }
```

> okay if I loop you in?

Sure!

**Comment by schuay** [comment]
> I tried, on Jakob's suggestion, enabling natives syntax, and calling %PerformMicrotaskCheckpoint(); in the test script, and it's worth noting it didn't seem to do the trick.

As shown in comment https://github.com/bcoe/c8/issues/66#issuecomment-545756340? I think you would need to call `%PerformMicrotaskCheckpoint();` at the end of the script, not the beginning.

Anyways, there are no promises or asyncs in your most recent example, so likely no connection to microtasks. (Note another example above did use async functions.)

**Comment by sigurdschneider** [comment]
We've altered coverage reporting to not report whitespace as uncovered in this case: https://bugs.chromium.org/p/v8/issues/detail?id=9952

Thanks for finding this issue und posting a repro!

**Comment by schuay** [comment]
I just want to point out that there is probably some issue in c8 causing the line containing `  function bar() {` to be reported as uncovered, even though V8 correctly reports the leading two spaces as uncovered and the `bar`, starting at the function keyword, as covered.

The fix Sigurd mentioned above is slightly orthogonal since it just fixes our 'report-trailling-whitespace-and-comments-after-return' optimization for functions with default-value-args.

@bcoe please double-check why c8 is reporting lines 4 and 5 as uncovered.

**Comment by bcoe** [comment]
The upstream V8 fixes have been landed in Node.js, and I have confirmed that this addresses this issue 👍 

@schuay I've opened a [tracking issue](https://github.com/istanbuljs/v8-to-istanbul/issues/81) for the hiccup with `v8-to-istanbul` (I think you're right that this is an actual issue).

@sigurdschneider thanks for this fix! this addresses a pretty nasty bug.
